import "./css/globals.css";
import "./css/main.css";
import { Nunito_Sans } from "next/font/google";
const mainFont = Nunito_Sans({weight: '400', subsets: ['latin']})

export const metadata = {
  title: {
    absolute: 'AudioVista | Pembelajaran Interaktif Tunarungu',
    default: 'AudioVista | Pembelajaran Interaktif Tunarungu',
    template: '%s | AudioVista'
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css"/>
      </head>
      <body className={mainFont.className}>{children}</body>
    </html>
  );
}
